### ISSUE TITLE
Server side generated code is not properly displayed in post shorten

### ISSUE THREAD

**Issue by deimosfr** [kakawait/hugo-tranquilpeak-theme#151] opened 2017-04-16 17:26 UTC
### Configuration

 - **Operating system with its version**: Arch Linux x64
 - **Browser with its version**: Google Chrome Version 57.0.2987.133 (64-bit)
 - **Hugo version**: v0.20.1
 - **Tranquilpeak version**: 0.3.1-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: no
 
### Actual behavior
When using server side highlighting code, in the postShorten-excerpt, code is generated in a h1 block which I think is not expected. I suggest to simply remove the code part in the post shorten to avoid issues.

Here is an example: http://imgur.com/3erA7y3

### Expected behavior
Code should appear correctly or should be removed.

### Steps to reproduce the behavior
Simply add code just in the firsts lines:
```
blabla
{{< highlight bash >}}
See it generated in h1
{{< /highlight >}}
```

**Comment by kakawait** [comment] 2017-04-19 20:13
@deimosfr I have some trouble to reproduce can you give me your `md` file?

**Comment by deimosfr** [comment] 2017-04-20 16:23
Of course:
```
---
title: 'Ansible: Neo4j role available on Ansible Galaxy'
author: Deimos
type: post
date: 2015-02-27T11:00:01+00:00
url: /2015/02/27/ansible-neo4j-role-available-on-ansible-galaxy/
image: /images/logo_neo4j.png
thumbnailImage: /thumbnails/logo_neo4j.png
thumbnailImagePosition: left
categories:
  - Ansible
  - Databases
  - Debian
  - Hi-Tech
  - Linux
  - NoSQL
  - SQL
tags:
  - Ansible
  - Databases
  - Debian
  - Hi-Tech
  - Linux
  - NoSQL
  - SQL

---
![no4j_logo](/images/logo_neo4j.png)
For a new project (will talk about it later), I needed to use Neo4J (graph database if you don't know it yet).

I tried to cover more features than the current existing Ansible roles available on Ansible Galaxy. More will come in the next weeks. I also tried to make it simple to install it and do not force dependencies at maximum. Here are parameters you can set:

{{< highlight bash >}}# Select neo4j version
neo4j_package: neo4j # community version
#neo4j_package: neo4j-advanced
#neo4j_package: neo4j-enterprise

# Neo4j spatial plugin
neo4j_install_spatial: false
neo4j_spatial_version: '0.13-neo4j-2.1.2'
neo4j_plugins_directory: '/usr/share/neo4j/plugins'

# java prerequisite
neo4j_install_java: false
neo4j_java_package_name: openjdk-7-jdk

# limits.conf
neo4j_update_limits: true
neo4j_nofile_value: 40000

# neo4j neostore mapped memory
neo4j_mm_nodestore: 25M
neo4j_mm_relationshipstore: 50M
neo4j_mm_propertystore: 90M
neo4j_mm_propertystore_strings: 130M
neo4j_mm_propertystore_arrays: 130M
neo4j_mm_index: 5M
neo4j_nm_index_keys: 5M
neo4j_cache_type: none

# server
neo4j_server_database_location: data/graph.db
neo4j_server_webserver_address: 127.0.0.1
neo4j_server_webserver_port: 7474
neo4j_server_webserver_https_enabled: false
neo4j_server_webserver_https_port: 7473
neo4j_server_webserver_https_cert_location: conf/ssl/snakeoil.cert
neo4j_server_webserver_https_key_location: conf/ssl/snakeoil.key
neo4j_server_webserver_https_keystore_location: data/keystore

# webadmin
neo4j_server_webadmin_rrdb_location: data/rrd
neo4j_server_webadmin_data_uri: /db/data/
neo4j_server_webadmin_management_uri: /db/manage/
neo4j_server_db_tuning_properties: conf/neo4j.properties
neo4j_server_manage_console_engines: shell
neo4j_server_database_mode: SINGLE

# logging
neo4j_server_http_log_enabled: false
neo4j_server_http_log_config: conf/neo4j-http-logging.xml
neo4j_keep_logical_logs: true
{{< /highlight >}}

You can find [the Ansible role for Neo4j here](https://galaxy.ansible.com/deimosfr/neo4j/), it manages all versions (community, enterprise...) and you can install Spatial plugin as well easilly.

Hope it will help
```

Live look: https://blog.deimos.fr/page/3/

**Comment by kakawait** [comment] 2017-04-21 09:43
thank I will check that asap

**Comment by kakawait** [comment] 2017-04-21 20:50
@deimosfr I found the issue but when it will be fixed content will look like (don't care about image I just don't have image that why it failed to load)

<img width="804" alt="screen shot 2017-04-21 at 22 46 52" src="https://cloud.githubusercontent.com/assets/275609/25295604/784ad5dc-26e4-11e7-8cb8-30cdb929fca5.png">

It can be better because it's _Hugo_ limitation that can't highlight on excerpt.

I will recommande you to use `<!--more-->` comment (see https://gohugo.io/content/summaries/) to remove highlight code from excerpt like following

```markdown
---
title: 'Ansible: Neo4j role available on Ansible Galaxy'
author: Deimos
type: post
date: 2015-02-27T11:00:01+00:00
url: /2015/02/27/ansible-neo4j-role-available-on-ansible-galaxy/
image: /images/logo_neo4j.png
thumbnailImage: /thumbnails/logo_neo4j.png
thumbnailImagePosition: left
categories:
  - Ansible
  - Databases
  - Debian
  - Hi-Tech
  - Linux
  - NoSQL
  - SQL
tags:
  - Ansible
  - Databases
  - Debian
  - Hi-Tech
  - Linux
  - NoSQL
  - SQL

---
![no4j_logo](/images/logo_neo4j.png)
For a new project (will talk about it later), I needed to use Neo4J (graph database if you don't know it yet).

I tried to cover more features than the current existing Ansible roles available on Ansible Galaxy. More will come in the next weeks. I also tried to make it simple to install it and do not force dependencies at maximum. Here are parameters you can set:

<!--more-->

{{< highlight bash >}}# Select neo4j version
neo4j_package: neo4j # community version
#neo4j_package: neo4j-advanced
#neo4j_package: neo4j-enterprise

# Neo4j spatial plugin
neo4j_install_spatial: false
neo4j_spatial_version: '0.13-neo4j-2.1.2'
neo4j_plugins_directory: '/usr/share/neo4j/plugins'

# java prerequisite
neo4j_install_java: false
neo4j_java_package_name: openjdk-7-jdk

# limits.conf
neo4j_update_limits: true
neo4j_nofile_value: 40000

# neo4j neostore mapped memory
neo4j_mm_nodestore: 25M
neo4j_mm_relationshipstore: 50M
neo4j_mm_propertystore: 90M
neo4j_mm_propertystore_strings: 130M
neo4j_mm_propertystore_arrays: 130M
neo4j_mm_index: 5M
neo4j_nm_index_keys: 5M
neo4j_cache_type: none

# server
neo4j_server_database_location: data/graph.db
neo4j_server_webserver_address: 127.0.0.1
neo4j_server_webserver_port: 7474
neo4j_server_webserver_https_enabled: false
neo4j_server_webserver_https_port: 7473
neo4j_server_webserver_https_cert_location: conf/ssl/snakeoil.cert
neo4j_server_webserver_https_key_location: conf/ssl/snakeoil.key
neo4j_server_webserver_https_keystore_location: data/keystore

# webadmin
neo4j_server_webadmin_rrdb_location: data/rrd
neo4j_server_webadmin_data_uri: /db/data/
neo4j_server_webadmin_management_uri: /db/manage/
neo4j_server_db_tuning_properties: conf/neo4j.properties
neo4j_server_manage_console_engines: shell
neo4j_server_database_mode: SINGLE

# logging
neo4j_server_http_log_enabled: false
neo4j_server_http_log_config: conf/neo4j-http-logging.xml
neo4j_keep_logical_logs: true
{{< /highlight >}}

You can find [the Ansible role for Neo4j here](https://galaxy.ansible.com/deimosfr/neo4j/), it manages all versions (community, enterprise...) and you can install Spatial plugin as well easilly.

Hope it will help
```

that will result to something like (don't care about image I just don't have image that why it failed to load)

<img width="824" alt="screen shot 2017-04-21 at 22 49 09" src="https://cloud.githubusercontent.com/assets/275609/25295688/dedd12c4-26e4-11e7-8d58-7ca30b777472.png">

**Comment by deimosfr** [comment] 2017-04-21 21:55
Looks good to me. Thanks for the tricks !

**Comment by deimosfr** [comment] 2017-04-21 22:04
However I can notice in this case that images are shown in the summary which is not expected :-/

**Comment by kakawait** [comment] 2017-04-22 06:47
The fact that image was not show was a bug... Since it's part of first line it will be part of excerpt

**Comment by jhabdas** [comment] 2017-04-22 09:16
https://gohugo.io/content/summaries/

**Comment by jhabdas** [comment] 2017-04-22 10:17
Not a Hugo bug, a design constraint which helps create better patterns for theme developers. More info and discussion on the Hugo discussion forums. Tag me there and I'll drop my .02 as to why this Design constraint is actually a misunderstood feature of Hugo.

**Closed** 2017-09-10 10:38 UTC
Labels: bug, fixed on develop
